# Generated by Django 4.2.3 on 2023-07-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Store_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
