# Generated by Django 4.2.3 on 2023-07-14 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Store_App', '0002_alter_product_product_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_section_name', models.CharField(max_length=200)),
                ('food_section_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_section_name', models.CharField(max_length=200)),
                ('product_section_description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(default='Default description'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('food_description', models.TextField()),
                ('food_price', models.FloatField()),
                ('food_cuantity', models.FloatField()),
                ('food_creation_date', models.DateField(auto_now_add=True)),
                ('food_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_Store_App.food_section')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_Store_App.product_section'),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
