# Generated by Django 4.2.2 on 2023-07-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Store_App', '0004_food_food_image_food_section_food_section_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Food_Section',
        ),
    ]
