# Generated by Django 4.2.2 on 2023-08-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Store_App', '0007_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_password',
            field=models.CharField(max_length=20),
        ),
    ]
